#!/bin/bash
# Lab 4 sysinfo

#checking for root privlege
if [ "$(id -u)" != "0" ]; then
	echo "Root is not active, and is required to work properly."
	echo "Please restart this script as root"
	exit 1
fi

#Gathering of items, referer to lab for more detail.
mydate=$(date)

#Temp File to optimize runtime. (Could be optimized further slightly)
lshw -class system >/tmp/sysinfo.$$ 2>/dev/null
lshw -class cpu >/tmp/cpuinfo.$$ 2>/dev/null
lshw -class video >/tmp/vidinfo.$$ 2>/dev/null
lshw -class network >/tmp/netinfo.$$ 2>/dev/null
lscpu >/tmp/cpuinfo2.$$ 2>/dev/null
source ./reportfunctions.sh
cat <<EOF
System Report generated by $USER on $mydate

System Description
------------------------
EOF

cpureport
computerreport
osreport
ramreport
videoreport
#diskreport
networkreport
#errormessage
